---

- name: install libsodium
  apt:
    deb: https://ftp.weheartwebsites.de/{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}/libsodium18_{{ php7fpm_libsodium_version }}_amd64.deb
  become: yes

- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - libsystemd0
    - libltdl7
    - libssl1.0.0
    - libicu55
    - libxml2
    - libbz2-1.0
    - libcurl3
    - libwebp5
    - libjpeg-turbo8
    - libpng12-0
    - libfreetype6
    - libmcrypt4
    - libedit2
    - libreadline5
    - libxslt1.1
    - libzip4
    - libmagickwand-6.q16-2
    - libhiredis0.13
    - libmemcached11
    - libmemcachedutil2
    - libc-client2007e
    - libkrb5-3
  become: yes
