---

- name: add backports
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - deb http://ftp.debian.org/debian jessie-backports main non-free contrib
    - deb http://ftp.debian.org/debian jessie-backports-sloppy main non-free contrib
  become: yes

- name: install libsodium
  apt:
    name: libsodium18
    default_release: jessie-backports-sloppy
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - libsystemd0
    - libltdl7
    - libssl1.0.0
    - libicu52
    - libxml2
    - libbz2-1.0
    - libcurl3
    - libwebp5
    - libpng12-0
    - libfreetype6
    - libmcrypt4
    - libedit2
    - libreadline6
    - libxslt1.1
    - libjpeg62-turbo
    - libzip2
    - libmagickwand-6.q16-2
    - libhiredis0.10
    - libmemcached11
    - libmemcachedutil2
    - libc-client2007e
    - libkrb5-3
  become: yes
